name: Main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Deploying"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use.
      - run: dotnet build
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Publish the package to Nuget
        run: dotnet nuget push UvaSoftware.Scanii/bin/Release/Uvasoftware.Scanii.*.nupkg -k ${NUGET_KEY} -s https://api.nuget.org/v3/index.json
        env: 
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
      - name: Releasing
        run: |
          VERSION=$(cat UvaSoftware.Scanii/*.csproj | grep '<Version>' | awk -F '>|<' '{print $3}')
          echo "###################  using version: v$VERSION ###################"

          # tag repo
          git config --global user.email "ci@uvasoftware.com"
          git config --global user.name "Github Actions"
          git tag -a v"${VERSION}" -m "Release by Github Actions v${VERSION}"
          git push origin v"${VERSION}"
